### PR TITLE
Add deployToken option for firebase for use with multiple accounts.

### PR DESCRIPTION
**Pull request by mileszim**
Additionally, change fireBaseAppName to firebase.appName to fit with config hash. **Does not break 'context.config.fireBaseAppName'**

### CODE REVIEW

**Comment by ibroadfo** [comment]
I won't get a chance to test this till tomorrow pm but it looks good on a visual scan. 

I wondered if we should default to using `process.env.FIREBASE_TOKEN`; thoughts?

**Comment by mileszim** [comment]
@ibroadfo I was thinking that would be a fine route to go, but it seems like the .env environments would start to get too confusing. In other words, FIREBASE_TOKEN is such a generic label it could mean anything, but FIREBASE_DEPLOY_TOKEN implies only one thing. If there is a benefit for FIREBASE_TOKEN my opinion is extremely weak so that's fine with me.

**Comment by mileszim** [comment]
Also FYI it works fine, I'm using it on a production project no sweat

**Comment by mileszim** [comment]
Oooooohhh that might make it a lot simpler of a change. Lemme rework this and resubmit. Good catch :)

**Comment by ibroadfo** [comment]
👍

**Comment by mileszim** [comment]
Ok it's been updated to use the native FIREBASE_TOKEN env var if available. I have it behind the config/environment.js var in case organizing your token stuff there is more preferable, but either works. I'll sing the usual dev song: "Works on my machine". lemme know if you hit snags. Readme is also updated with both use cases

**Comment by ibroadfo** [comment]
Apologies for being a bit slow at handling this; I'm currently travelling so don't have reliable interwubs.

I think this is looking good! I noticed that the readme is mentioning `config/environment.js` where I'd expect it to be `config/deploy.js`; would that be right?

Hope this doesn't seem like nitpicking! :)

**Comment by mileszim** [comment]
@ibroadfo my b! changed to config/deploy.js, you were totally right about that since as one option I said to put the token in .env.deploy.production which would have only shown up in that file. Should be good to go I hope

**Comment by ibroadfo** [comment]
Thanks! This should be really useful for people.

**Comment by ibroadfo** [comment]
released! 😸

**Pull request merged**
